//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunExecutable
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPLICATION_LOG
    {
        public int LogID { get; set; }
        public string ApplicationName { get; set; }
        public string ApplicationType { get; set; }
        public string InnerException { get; set; }
        public string StackTrace { get; set; }
        public string ApplicationMessage { get; set; }
        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> IsError { get; set; }
    }
}
