//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunExecutable
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Programs
    {
        public int ID { get; set; }
        public Nullable<int> Customer_ID { get; set; }
        public string Customer_Name { get; set; }
        public string Program_RunTime { get; set; }
        public string POC { get; set; }
        public string Executable_Path { get; set; }
        public string OutputFiles_Path { get; set; }
        public string Comments { get; set; }
    }
}
