//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RunExecutable
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCustomerEmail
    {
        public short CustomerEmailID { get; set; }
        public string ShortName { get; set; }
        public string ClientName { get; set; }
        public string EmailList { get; set; }
        public string EmailSubject { get; set; }
        public string EmailText { get; set; }
    }
}
